### ISSUE TITLE
Ajax class returning the DOMWindow

### ISSUE THREAD

**Issue by ghost** [72lions/FrameworkJS#6]
Your ajax class is returning the DOMWindow "this" instead of your object. On a side note, I would also drop all IE7- support (e.g. `new ActiveXObject("Microsoft.XMLHTTP")`).

**Comment by 72lions** [comment]
I am thinking of keeping the IE7 support for now since I am testing it on a project that has to be functional on IE7+. Hopefully in the future I will drop the IE7 support!
